version: "3.9"
services:
  node_edulyst_api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    working_dir: /app
    stdin_open: true
    tty: true
    command: npm run dev

volumes:
  node_modules: