version: "3.9"
services:
  node_edulyst_api:
    image: techvins/repo:node_edulyst_api
    working_dir: /app
    stdin_open: true
    tty: true

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

networks:
  default:
    external:
      name: techvins-network